<?php


// LA FORMA EN QUE SE CREA UNA COOKIE ES CON LA FUNCIÓN setcookie().
// EL PRIMER PARÁMETRO ES EL NOMBRE DE LA COOKIE
// EL SEGUNDO ES LA FORMA EN QUE SE VA A RECIBIR LA COOKIE
// EL TERCER PARÁMETRO RECIBE LA DURACIÓN DE LA COOKIE
// LA FUNCIÓN time() NOS DEVUELVE LA FECHA UNIX ACTUAL. LA FECHA UNIX ES UN MÉTODO DE MEDIDA QUE CUENTA
// LOS SEGUNDOS DESDE EL 1970
// AL DECIR time() + 86400 ESTAMOS DICIENDO QUE DURE UN DÍA, YA QUE 86400s = 24h
// EL CUARTO PARÁMETRO DICE EN QUÉ DIRECTORIO PUEDE ESTAR LA COOKIE. SI AGREGAMOS UN / VA A SER USADA EN TODO EL
// DIRECTORIO EN EL QUE ESTÁ EL DOCUMENTO EN EL QUE FUE CREADO. SI NO SE ESPECIFICA SOLO EXISTE PARA ESTE ARCHIVO

setcookie("idiomaSolicitado", $_GET['idioma'], time()+86400, "/");
header("location:  6_usar.php")

?>