<?php

// SIEMPRE QUE SE TRABAJA CON SESIONES PRIMERO DEBEMOS INICIARLA CON LA FUNCIÓN: 
session_start();


// EN CASO DE QUE LA VARIABLE ES FALSE, ENTONCES SE REDIRECCIONA PARA ELIMINAR LA SESIÓN. PARA MÁS 
// EXPLICACIÓN IR A ARCHIVOS PROTEGIDOS

if (!$_SESSION['autentificado']) {
    header('location: 3_salir.php');
}

?>